# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.IntegerField(help_text='ejudge user id', primary_key=True, serialize=False)),
                ('bonuses', models.IntegerField(default=0, help_text='bonuses available to spend')),
                ('username', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
