# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256, verbose_name='Полное название группы')),
                ('short_name', models.CharField(max_length=256, verbose_name='Краткое название группы')),
                ('standings', models.BooleanField(default=True, verbose_name='Показывать ссылку на сводную таблицу')),
                ('reg_contest', models.IntegerField(verbose_name='Контест с участниками')),
            ],
            options={
                'verbose_name': 'группа',
                'verbose_name_plural': 'группы',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='имя пользователя'),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Group'),
        ),
    ]
