# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170725_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('cost', models.IntegerField(verbose_name='Цена')),
                ('stock', models.IntegerField(verbose_name='В наличии')),
                ('picture', models.ImageField(upload_to='prizes')),
            ],
            options={
                'verbose_name_plural': 'призы',
                'verbose_name': 'приз',
            },
        ),
    ]
