# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170801_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='statement',
            field=models.FileField(blank=True, null=True, upload_to=main.models.random_statement_path, verbose_name='Условие'),
        ),
    ]
