# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170803_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='full_name',
            field=models.CharField(max_length=128, verbose_name='Полное название группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='short_name',
            field=models.CharField(max_length=128, verbose_name='Краткое название группы'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(help_text='Например, "Тренировка 01"', max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lessonattachment',
            name='name',
            field=models.CharField(help_text='Например, "План лекции"', max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='Логин'),
        ),
    ]
