# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 07:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20170804_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoreward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob', models.CharField(db_index=True, max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='autorewards',
            field=models.TextField(blank=True, default='', help_text='<a href="/static/rewards.html">Справка</a>', verbose_name='Автонаграды'),
        ),
        migrations.AddField(
            model_name='autoreward',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Lesson'),
        ),
        migrations.AddField(
            model_name='autoreward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
