#!/usr/bin/python3
import sys

with open(sys.argv[1], 'r') as input_file:
    limit = int(input_file.read())

data = set()

for a in range(1, limit + 1):
    for b in range(a + 1, limit + 1):
        for c in range(b + 1, limit + 1):
            if pow(a, 2) + pow(b, 2) == pow(c, 2):
                data.add((a, b, c))


user_data = set()

with open(sys.argv[2], 'r') as output_file:
    raw_data = output_file.readlines()
    for line in raw_data:
        user_chunk = tuple(map(int, line.split()))
        user_data.add(tuple(user_chunk))

if data == user_data:
    exit(0)
else:
    print("{} is not equal {}\n".format(str(sorted(data)), str(sorted(user_data))), file=sys.stderr)
    exit(5)
